### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by headupinclouds** [comment]
```
[hunter ** FATAL ERROR **] Building package from source is disabled (dir: /home/travis/.hunter/_Base/de2b0d4/dce890d/6db21fa/Build/aglet)
[hunter ** FATAL ERROR **] [Directory:/home/travis/.hunter/_Base/Download/Hunter/0.19.134/de2b0d4/Unpacked/cmake/projects/aglet]
```

**Comment by ruslo** [comment]
> Building package from source is disabled

Uploading missing packages, will be fixed soon.

The only problem I see is about Android:
```
/.../drishti_hunter_test/src/app/face/FaceTrackerFactoryJson.cpp:17:37: fatal error: drishti_stdlib_string.h: No such file or directory
```

**Comment by headupinclouds** [comment]
Building latest now.

**Comment by ruslo** [comment]
> [hunter ** FATAL ERROR **] Building package from source is disabled (dir: /Users/travis/.hunter/_Base/de2b0d4/48f613a/ca2ddd4/Build/aglet)

Cache miss on iOS, uploading:
* https://travis-ci.org/ingenue/hunter/builds/293233039?utm_source=github_status&utm_medium=notification

**Comment by ruslo** [comment]
> Building package from source is disabled (dir: /Users/travis/.hunter/_Base/de2b0d4/48f613a/ca2ddd4/Build/Boost/__system)

Boost cache miss, uploading:
* https://travis-ci.org/ingenue/hunter/builds/293297129

**Pull request merged**
